### ISSUE TITLE
Mysql client is missing

### ISSUE THREAD

**Issue by eniac111** [pretalx/pretalx-docker#71]
The current container build is broken because the `mysqlclient` python package is not installed. Here is the log:

```
pretalx  | fatal: not a git repository (or any of the parent directories): .git
pretalx  | Traceback (most recent call last):
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 16, in <module>
pretalx  |     import MySQLdb as Database
pretalx  | ModuleNotFoundError: No module named 'MySQLdb'
pretalx  | 
pretalx  | The above exception was the direct cause of the following exception:
pretalx  | 
pretalx  | Traceback (most recent call last):
pretalx  |   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
pretalx  |     return _run_code(code, main_globals, None,
pretalx  |   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
pretalx  |     exec(code, run_globals)
pretalx  |   File "/pretalx/src/pretalx/__main__.py", line 9, in <module>
pretalx  |     execute_from_command_line(sys.argv)
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
pretalx  |     utility.execute()
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 416, in execute
pretalx  |     django.setup()
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
pretalx  |     apps.populate(settings.INSTALLED_APPS)
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
pretalx  |     app_config.import_models()
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/apps/config.py", line 269, in import_models
pretalx  |     self.models_module = import_module(models_module_name)
pretalx  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
pretalx  |     return _bootstrap._gcd_import(name[level:], package, level)
pretalx  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
pretalx  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
pretalx  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
pretalx  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
pretalx  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
pretalx  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/models.py", line 5, in <module>
pretalx  |     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/base_user.py", line 40, in <module>
pretalx  |     class AbstractBaseUser(models.Model):
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 143, in __new__
pretalx  |     new_class.add_to_class("_meta", Options(meta, app_label))
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 371, in add_to_class
pretalx  |     value.contribute_to_class(cls, name)
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/options.py", line 231, in contribute_to_class
pretalx  |     self.db_table, connection.ops.max_name_length()
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/utils/connection.py", line 15, in __getattr__
pretalx  |     return getattr(self._connections[self._alias], item)
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/utils/connection.py", line 62, in __getitem__
pretalx  |     conn = self.create_connection(alias)
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 193, in create_connection
pretalx  |     backend = load_backend(db["ENGINE"])
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 113, in load_backend
pretalx  |     return import_module("%s.base" % backend_name)
pretalx  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
pretalx  |     return _bootstrap._gcd_import(name[level:], package, level)
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 18, in <module>
pretalx  |     raise ImproperlyConfigured(
pretalx  | django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
pretalx  | Did you install mysqlclient?
```

**Comment by eniac111** [comment]
Here is a pull request: https://github.com/pretalx/pretalx-docker/pull/72

**Comment by saschafoerster** [comment]
The support for MySQL has been dropped. Is this maybe the reason why it was removed?

https://pretalx.com/p/news/releasing-pretalx-2024-3-0/

**Comment by eniac111** [comment]
Right, I saw it after the PR and made my own container from scratch. I'll update you once everything is ready.
